// Audiobook listening time fields + compact Stats tracker.
(function(){
 if(window.__audiobookStatsInitialized)return;window.__audiobookStatsInitialized=true;
 const DETAIL_KEY='bookDetailOverrides',COLOR_KEY='statsAudiobookColors';
 function loadDetails(){try{return JSON.parse(localStorage.getItem(DETAIL_KEY)||'{}')}catch(e){return {}}}
 function hydrate(){const d=loadDetails();books.forEach(b=>{if(d[b.id]&&d[b.id].audioMinutes!==undefined)b.audioMinutes=Number(d[b.id].audioMinutes)||0})}hydrate();
 function isAudio(b){return /audio/.test(String(b.format||'').toLowerCase())}
 function saveMinutes(book,mins){const d=loadDetails();(d[book.id]||(d[book.id]={})).audioMinutes=Math.max(0,Math.round(mins||0));localStorage.setItem(DETAIL_KEY,JSON.stringify(d));book.audioMinutes=Math.max(0,Math.round(mins||0));window.dispatchEvent(new Event('library-stats-updated'))}
 const style=document.createElement('style');style.textContent=`.audio-time-row{margin:-8px 0 18px;padding:12px;background:#17352c;border:1px solid #927e5266;border-radius:8px}.audio-time-label{font-size:11px;letter-spacing:1px;color:#a99772;margin-bottom:8px}.audio-time-fields{display:grid;grid-template-columns:1fr 1fr;gap:8px}.audio-time-field{display:grid;gap:4px}.audio-time-field span{font-size:10px;color:#8f8063}.audio-time-input{width:100%;background:#203c32;border:1px solid #927e5266;color:#eee0bd;border-radius:6px;padding:9px}.audio-stat-card{grid-column:auto!important}.audio-stat-layout{display:grid;grid-template-columns:190px 1fr;gap:20px;align-items:center}.audio-clock{width:170px;height:170px;border-radius:50%;position:relative;margin:auto;box-shadow:0 8px 22px #0005}.audio-clock:after{content:'';position:absolute;inset:34px;border-radius:50%;background:#122d25}.audio-clock-center{position:absolute;inset:0;z-index:1;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.audio-hours{font-size:31px;color:#eadcb8;line-height:1}.audio-minutes{font-size:13px;color:#c8b68e;margin-top:5px}.audio-caption{font-size:9px;letter-spacing:1.4px;color:#a99772;margin-top:6px}.audio-big-stat{font-size:21px;color:#eadcb8;margin-bottom:5px}.audio-substat{color:#a99772;font-size:11px;margin-bottom:12px}.audio-color-controls{display:flex;gap:12px;flex-wrap:wrap;margin-top:12px;padding-top:11px;border-top:1px solid #8e794c33}.audio-color-control{display:flex;align-items:center;gap:7px;color:#bca978;font-size:11px}.audio-color-control input{width:28px;height:28px;border:0;background:transparent;padding:0}@media(max-width:700px){.audio-stat-layout{grid-template-columns:1fr}}`;document.head.appendChild(style);
 function addAudioFields(book){let old=document.querySelector('#audioTimeRow');if(old)old.remove();if(!isAudio(book))return;const anchor=document.querySelector('#finishedDateRow')||document.querySelector('#contentRatingRow');if(!anchor)return;const total=Math.max(0,Number(book.audioMinutes)||0),hrs=Math.floor(total/60),mins=total%60;const row=document.createElement('div');row.id='audioTimeRow';row.className='audio-time-row';row.innerHTML=`<div class="audio-time-label">AUDIOBOOK LISTENING TIME</div><div class="audio-time-fields"><label class="audio-time-field"><span>HOURS</span><input id="audioHours" class="audio-time-input" type="number" min="0" step="1" value="${hrs}"></label><label class="audio-time-field"><span>MINUTES</span><input id="audioMinutes" class="audio-time-input" type="number" min="0" max="59" step="1" value="${mins}"></label></div><div style="font-size:10px;color:#8f8063;margin-top:7px">Enter the time you listened to this audiobook. It is added to your Stats total.</div>`;anchor.insertAdjacentElement('afterend',row);const h=row.querySelector('#audioHours'),m=row.querySelector('#audioMinutes');function save(){let hv=Math.max(0,Number(h.value)||0),mv=Math.max(0,Number(m.value)||0);if(mv>=60){hv+=Math.floor(mv/60);mv=mv%60;h.value=hv;m.value=mv}saveMinutes(book,hv*60+mv)}h.onchange=save;m.onchange=save}
 const priorOpen=window.openBook;window.openBook=function(book){priorOpen(book);hydrate();setTimeout(()=>addAudioFields(book),0)};
 document.addEventListener('change',e=>{if(e.target&&e.target.id==='inlineFormat'){setTimeout(()=>{const title=document.querySelector('#inlineBookTitle')?.value,author=document.querySelector('#inlineBookAuthor')?.value;const b=books.find(x=>x.title===title&&x.author===author);if(b)addAudioFields(b);window.dispatchEvent(new Event('library-stats-updated'))},0)}});
 const grid=document.querySelector('#statsReadingGrid');if(!grid)return;
 let palette=Object.assign({listened:'#c7a86b',remaining:'#315443'},JSON.parse(localStorage.getItem(COLOR_KEY)||'{}'));
 const card=document.createElement('section');card.className='reading-chart-card audio-stat-card';card.innerHTML=`<h2>Audiobook Listening</h2><div class="reading-chart-sub">Accumulated listening time</div><div class="audio-stat-layout"><div class="audio-clock" id="audioClock"><div class="audio-clock-center"><div class="audio-hours" id="audioHoursTotal">0 hrs</div><div class="audio-minutes" id="audioMinutesRemainder">0 min</div><div class="audio-caption">LISTENED</div></div></div><div><div class="audio-big-stat" id="audioTotalMinutes">0 total minutes</div><div class="audio-substat" id="audioBookSummary">0 audiobooks with listening time</div><div class="reading-legend"><div class="reading-legend-row"><span class="reading-marker" id="audioListenedMarker"></span><span class="reading-legend-name">Hours listened</span><span class="reading-legend-count" id="audioLegendHours">0</span></div><div class="reading-legend-row"><span class="reading-marker" id="audioRemainingMarker"></span><span class="reading-legend-name">Next hour</span><span class="reading-legend-count" id="audioLegendProgress">0%</span></div></div><div class="audio-color-controls"><label class="audio-color-control">Listened <input id="audioListenedColor" type="color"></label><label class="audio-color-control">Remaining <input id="audioRemainingColor" type="color"></label></div></div></div>`;
 const goal=grid.querySelector('.goal-card');if(goal)grid.insertBefore(card,goal);else grid.appendChild(card);
 const lc=card.querySelector('#audioListenedColor'),rc=card.querySelector('#audioRemainingColor');lc.value=palette.listened;rc.value=palette.remaining;
 function render(){hydrate();const audio=books.filter(isAudio),withTime=audio.filter(b=>Number(b.audioMinutes)>0),total=audio.reduce((sum,b)=>sum+(Number(b.audioMinutes)||0),0),hours=Math.floor(total/60),mins=total%60;/* Ring is a cumulative-time gauge: every full hour is filled, and the current partial hour shows its progress. Exact full hours remain 100% filled instead of appearing empty. */const pct=total===0?0:(mins===0?100:mins/60*100),remainingPct=total===0?100:100-pct;card.querySelector('#audioHoursTotal').textContent=hours+' hr'+(hours===1?'':'s');card.querySelector('#audioMinutesRemainder').textContent=mins+' min';card.querySelector('#audioTotalMinutes').textContent=total.toLocaleString()+' total minute'+(total===1?'':'s');card.querySelector('#audioBookSummary').textContent=withTime.length+' of '+audio.length+' audiobook'+(audio.length===1?'':'s')+' have listening time entered';card.querySelector('#audioLegendHours').textContent=hours;card.querySelector('#audioLegendProgress').textContent=Math.round(pct)+'%';card.querySelector('#audioListenedMarker').style.background=palette.listened;card.querySelector('#audioRemainingMarker').style.background=palette.remaining;card.querySelector('#audioClock').style.background=total?`conic-gradient(${palette.listened} 0 ${pct}%,${palette.remaining} ${pct}% 100%)`:`conic-gradient(${palette.remaining} 0 100%)`}
 lc.oninput=e=>{palette.listened=e.target.value;localStorage.setItem(COLOR_KEY,JSON.stringify(palette));render()};rc.oninput=e=>{palette.remaining=e.target.value;localStorage.setItem(COLOR_KEY,JSON.stringify(palette));render()};window.addEventListener('library-stats-updated',render);document.querySelectorAll('.nav button').forEach(b=>{if(b.dataset.view==='stats')b.addEventListener('click',()=>setTimeout(render,0))});render();
})();