// Audiobook listening time fields + compact total-time Stats card.
(function(){
 if(window.__audiobookStatsInitialized)return;window.__audiobookStatsInitialized=true;
 const DETAIL_KEY='bookDetailOverrides';
 function loadDetails(){try{return JSON.parse(localStorage.getItem(DETAIL_KEY)||'{}')}catch(e){return {}}}
 function hydrate(){const d=loadDetails();books.forEach(b=>{if(d[b.id]&&d[b.id].audioMinutes!==undefined)b.audioMinutes=Number(d[b.id].audioMinutes)||0})}hydrate();
 function isAudio(b){return /audio/.test(String(b.format||'').toLowerCase())}
 function saveMinutes(book,mins){const d=loadDetails();(d[book.id]||(d[book.id]={})).audioMinutes=Math.max(0,Math.round(mins||0));localStorage.setItem(DETAIL_KEY,JSON.stringify(d));book.audioMinutes=Math.max(0,Math.round(mins||0));window.dispatchEvent(new Event('library-stats-updated'))}
 const style=document.createElement('style');style.textContent=`.audio-time-row{margin:-8px 0 18px;padding:12px;background:#17352c;border:1px solid #927e5266;border-radius:8px}.audio-time-label{font-size:11px;letter-spacing:1px;color:#a99772;margin-bottom:8px}.audio-time-fields{display:grid;grid-template-columns:1fr 1fr;gap:8px}.audio-time-field{display:grid;gap:4px}.audio-time-field span{font-size:10px;color:#8f8063}.audio-time-input{width:100%;background:#203c32;border:1px solid #927e5266;color:#eee0bd;border-radius:6px;padding:9px}.audio-stat-card{grid-column:auto!important;min-height:300px;display:flex;flex-direction:column}.audio-total-wrap{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:16px 10px 22px}.audio-total-time{font-size:54px;line-height:1;color:#d7b66e;margin-bottom:10px}.audio-total-time .audio-small-unit{font-size:25px;color:#eadcb8}.audio-total-label{font-size:11px;letter-spacing:2px;color:#a99772;margin-bottom:22px}.audio-total-minutes{font-size:18px;color:#eadcb8;padding-top:18px;border-top:1px solid #8e794c33;width:min(330px,90%)}.audio-book-summary{font-size:11px;color:#a99772;margin-top:7px}@media(max-width:700px){.audio-total-time{font-size:44px}}`;document.head.appendChild(style);
 function addAudioFields(book){let old=document.querySelector('#audioTimeRow');if(old)old.remove();if(!isAudio(book))return;const anchor=document.querySelector('#finishedDateRow')||document.querySelector('#contentRatingRow');if(!anchor)return;const total=Math.max(0,Number(book.audioMinutes)||0),hrs=Math.floor(total/60),mins=total%60;const row=document.createElement('div');row.id='audioTimeRow';row.className='audio-time-row';row.innerHTML=`<div class="audio-time-label">AUDIOBOOK LISTENING TIME</div><div class="audio-time-fields"><label class="audio-time-field"><span>HOURS</span><input id="audioHours" class="audio-time-input" type="number" min="0" step="1" value="${hrs}"></label><label class="audio-time-field"><span>MINUTES</span><input id="audioMinutes" class="audio-time-input" type="number" min="0" max="59" step="1" value="${mins}"></label></div><div style="font-size:10px;color:#8f8063;margin-top:7px">Enter the time you listened to this audiobook. It is added to your Stats total.</div>`;anchor.insertAdjacentElement('afterend',row);const h=row.querySelector('#audioHours'),m=row.querySelector('#audioMinutes');function save(){let hv=Math.max(0,Number(h.value)||0),mv=Math.max(0,Number(m.value)||0);if(mv>=60){hv+=Math.floor(mv/60);mv=mv%60;h.value=hv;m.value=mv}saveMinutes(book,hv*60+mv)}h.onchange=save;m.onchange=save}
 const priorOpen=window.openBook;window.openBook=function(book){priorOpen(book);hydrate();setTimeout(()=>addAudioFields(book),0)};
 document.addEventListener('change',e=>{if(e.target&&e.target.id==='inlineFormat'){setTimeout(()=>{const title=document.querySelector('#inlineBookTitle')?.value,author=document.querySelector('#inlineBookAuthor')?.value;const b=books.find(x=>x.title===title&&x.author===author);if(b)addAudioFields(b);window.dispatchEvent(new Event('library-stats-updated'))},0)}});
 const grid=document.querySelector('#statsReadingGrid');if(!grid)return;
 const card=document.createElement('section');card.className='reading-chart-card audio-stat-card';card.innerHTML=`<h2>Audiobook Listening</h2><div class="reading-chart-sub">Total time accumulated across your audiobook collection</div><div class="audio-total-wrap"><div class="audio-total-time"><span id="audioHoursTotal">0</span> <span class="audio-small-unit">hrs</span> <span id="audioMinutesRemainder">0</span> <span class="audio-small-unit">min</span></div><div class="audio-total-label">TOTAL LISTENING TIME</div><div class="audio-total-minutes" id="audioTotalMinutes">0 total minutes</div><div class="audio-book-summary" id="audioBookSummary">0 audiobooks with listening time entered</div></div>`;
 const goal=grid.querySelector('.goal-card');if(goal)grid.insertBefore(card,goal);else grid.appendChild(card);
 function render(){hydrate();const audio=books.filter(isAudio),withTime=audio.filter(b=>Number(b.audioMinutes)>0),total=audio.reduce((sum,b)=>sum+(Number(b.audioMinutes)||0),0),hours=Math.floor(total/60),mins=total%60;card.querySelector('#audioHoursTotal').textContent=hours.toLocaleString();card.querySelector('#audioMinutesRemainder').textContent=mins;card.querySelector('#audioTotalMinutes').textContent=total.toLocaleString()+' total minute'+(total===1?'':'s');card.querySelector('#audioBookSummary').textContent=withTime.length+' of '+audio.length+' audiobook'+(audio.length===1?'':'s')+' have listening time entered'}
 window.addEventListener('library-stats-updated',render);document.querySelectorAll('.nav button').forEach(b=>{if(b.dataset.view==='stats')b.addEventListener('click',()=>setTimeout(render,0))});render();
})();