// Manual add-book and wishlist workflow. User-created books persist in this browser.
(function(){
  const BOOK_KEY='manualBooks', WISH_KEY='wishlistBooks';
  const manualBooks=JSON.parse(localStorage.getItem(BOOK_KEY)||'[]');
  let wishlist=JSON.parse(localStorage.getItem(WISH_KEY)||'[]');
  manualBooks.forEach(b=>{if(!books.some(x=>String(x.id)===String(b.id)))books.push(b)});
  manualBooks.forEach(b=>{if(!order.includes(b.id))order.push(b.id)});
  localStorage.setItem('bookOrder',JSON.stringify(order));

  const style=document.createElement('style');style.textContent=`
  .add-book-btn{background:#6a4c2d;border:1px solid #c7a86b88;color:#f1e3bd;border-radius:20px;padding:9px 14px;cursor:pointer}.add-book-btn:hover{background:#795936}.book-modal-backdrop{position:fixed;inset:0;background:#020b08b8;z-index:40;display:none;align-items:center;justify-content:center;padding:18px}.book-modal-backdrop.open{display:flex}.book-modal{width:min(560px,96vw);max-height:90vh;overflow:auto;background:#102a23;border:1px solid #a88c56;border-radius:12px;box-shadow:0 24px 60px #000c;padding:22px}.book-modal-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:15px}.book-modal h2{margin:0;color:#ead8aa;font-weight:normal}.book-modal-close{background:none;border:0;color:#ead8aa;font-size:26px;cursor:pointer}.book-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.book-field{display:flex;flex-direction:column;gap:5px;font-size:12px;color:#cfc3a5}.book-field.full{grid-column:1/-1}.book-field input,.book-field select,.book-field textarea{background:#0b211c;border:1px solid #8f7a4d66;color:#eee0bd;border-radius:6px;padding:9px}.book-field textarea{min-height:75px;resize:vertical}.book-destination{display:flex;gap:8px}.dest-btn{flex:1;background:#17352c;border:1px solid #8f7a4d66;color:#d8c9a6;border-radius:7px;padding:9px;cursor:pointer}.dest-btn.active{background:#6a4c2d;border-color:#c7a86b;color:#fff0c8}.book-save{width:100%;margin-top:16px;background:#6a4c2d;border:1px solid #c7a86b88;color:#fff0c8;border-radius:7px;padding:11px;cursor:pointer}.wishlist-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:14px}.wish-card{background:#122d25;border:1px solid #8e794c44;border-radius:8px;padding:16px}.wish-card b{color:#e6d5ad}.wish-actions{display:flex;gap:7px;margin-top:12px}.wish-actions button{flex:1;background:#203c32;border:1px solid #927e5266;color:#ddd0af;border-radius:5px;padding:7px;cursor:pointer}.wish-actions .acquire{background:#5a4329}@media(max-width:600px){.book-form{grid-template-columns:1fr}.book-field.full{grid-column:auto}}
  `;document.head.appendChild(style);

  const modal=document.createElement('div');modal.className='book-modal-backdrop';modal.innerHTML=`<div class="book-modal"><div class="book-modal-head"><h2>Add a Book</h2><button class="book-modal-close">×</button></div><form id="manualBookForm"><div class="book-form"><div class="book-field full"><label>Add to</label><div class="book-destination"><button type="button" class="dest-btn active" data-dest="library">My Library</button><button type="button" class="dest-btn" data-dest="wishlist">Wishlist</button></div></div><div class="book-field full"><label>Title *</label><input id="newTitle" required></div><div class="book-field"><label>Author</label><input id="newAuthor"></div><div class="book-field"><label>Genre</label><input id="newGenre" placeholder="Fantasy, Romance…"></div><div class="book-field"><label>Format</label><select id="newFormat"><option>Hardcover</option><option>Paperback</option><option>Kindle/eBook</option><option>Audiobook</option><option>Other</option></select></div><div class="book-field"><label>Status</label><select id="newStatus"><option value="false">Unread</option><option value="true">Read</option></select></div><div class="book-field"><label>Rating</label><select id="newRating"><option value="0">Not rated</option><option value="1">1 star</option><option value="2">2 stars</option><option value="3">3 stars</option><option value="4">4 stars</option><option value="5">5 stars</option></select></div><div class="book-field"><label>Spice level</label><select id="newSpice"><option value="0">0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></div><div class="book-field full"><label>Notes</label><textarea id="newNotes" placeholder="Optional notes…"></textarea></div></div><button class="book-save" type="submit">Add Book</button></form></div>`;document.body.appendChild(modal);
  let destination='library';
  modal.querySelectorAll('.dest-btn').forEach(b=>b.onclick=()=>{destination=b.dataset.dest;modal.querySelectorAll('.dest-btn').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('#newStatus').disabled=destination==='wishlist';document.querySelector('#newRating').disabled=destination==='wishlist';document.querySelector('#newSpice').disabled=destination==='wishlist'});
  modal.querySelector('.book-modal-close').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
  function openAdd(dest){destination=dest||'library';modal.querySelectorAll('.dest-btn').forEach(x=>x.classList.toggle('active',x.dataset.dest===destination));document.querySelector('#newStatus').disabled=destination==='wishlist';document.querySelector('#newRating').disabled=destination==='wishlist';document.querySelector('#newSpice').disabled=destination==='wishlist';modal.classList.add('open');document.querySelector('#newTitle').focus()}
  function colorFor(id){const palette=['#563329','#233a32','#74543b','#25483d','#6a3f35','#25343a','#526146','#7a493d','#3d563c','#3c3035'];return palette[Math.abs(Number(String(id).slice(-2)))%palette.length]}
  function persistManual(){localStorage.setItem(BOOK_KEY,JSON.stringify(books.filter(b=>String(b.id).startsWith('m'))))}
  function refreshAll(){if(typeof window.renderShelves==='function')window.renderShelves();if(typeof window.renderCards==='function')window.renderCards();renderWishlist();const total=document.querySelector('#total');if(total)total.textContent=books.length;const read=document.querySelector('#readCount');if(read)read.textContent=books.filter(b=>b.read).length}
  modal.querySelector('#manualBookForm').onsubmit=e=>{e.preventDefault();const title=document.querySelector('#newTitle').value.trim();if(!title)return;const id='m'+Date.now();const b={id,title,author:document.querySelector('#newAuthor').value.trim()||'Unknown Author',genre:document.querySelector('#newGenre').value.trim()||'Uncategorized',format:document.querySelector('#newFormat').value,read:document.querySelector('#newStatus').value==='true',rating:Number(document.querySelector('#newRating').value),spice:Number(document.querySelector('#newSpice').value),color:colorFor(id)};const note=document.querySelector('#newNotes').value.trim();if(destination==='wishlist'){wishlist.push({...b,read:false,rating:0,spice:0});localStorage.setItem(WISH_KEY,JSON.stringify(wishlist))}else{books.push(b);order.push(b.id);localStorage.setItem('bookOrder',JSON.stringify(order));persistManual();if(note){notes[b.id]=note;localStorage.setItem('bookNotes',JSON.stringify(notes))}}e.target.reset();destination='library';modal.classList.remove('open');refreshAll()};

  const shelfTop=document.querySelector('#shelf .top');if(shelfTop&&!document.querySelector('#addBookBtn')){const b=document.createElement('button');b.id='addBookBtn';b.className='add-book-btn';b.textContent='+ Add Book';b.onclick=()=>openAdd('library');shelfTop.appendChild(b)}
  const libTop=document.querySelector('#library .top');if(libTop&&!document.querySelector('#addBookLibBtn')){const b=document.createElement('button');b.id='addBookLibBtn';b.className='add-book-btn';b.textContent='+ Add Book';b.onclick=()=>openAdd('library');libTop.appendChild(b)}
  const wish=document.querySelector('#wishlist');const wishTop=wish.querySelector('.top');const wb=document.createElement('button');wb.className='add-book-btn';wb.textContent='+ Add to Wishlist';wb.onclick=()=>openAdd('wishlist');wishTop.appendChild(wb);const oldEmpty=wish.querySelector('.empty');if(oldEmpty)oldEmpty.remove();const wishGrid=document.createElement('div');wishGrid.id='wishlistGrid';wishGrid.className='wishlist-grid';wish.appendChild(wishGrid);
  function renderWishlist(){wishGrid.innerHTML='';if(!wishlist.length){wishGrid.innerHTML='<div class="empty">♡ Your future book haul will live here.</div>';return}wishlist.forEach(b=>{const c=document.createElement('div');c.className='wish-card';c.innerHTML=`<b>${b.title}</b><br><small>${b.author||''}</small><p>${b.genre||'Uncategorized'} · ${b.format||'Other'}</p><div class="wish-actions"><button class="acquire">Move to Library</button><button class="remove-wish">Remove</button></div>`;c.querySelector('.acquire').onclick=()=>{wishlist=wishlist.filter(x=>x.id!==b.id);localStorage.setItem(WISH_KEY,JSON.stringify(wishlist));b.id='m'+Date.now();books.push(b);order.push(b.id);localStorage.setItem('bookOrder',JSON.stringify(order));persistManual();refreshAll()};c.querySelector('.remove-wish').onclick=()=>{wishlist=wishlist.filter(x=>x.id!==b.id);localStorage.setItem(WISH_KEY,JSON.stringify(wishlist));renderWishlist()};wishGrid.appendChild(c)})}
  window.openManualBookAdd=openAdd;renderWishlist();refreshAll();
})();