// Free-form per-book tags shown beneath My Notes.
(function(){
 if(window.__bookTagsInitialized)return;window.__bookTagsInitialized=true;
 const KEY='bookDetailOverrides';let currentBook=null;
 function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
 function normalize(tags){const seen=new Set();return (Array.isArray(tags)?tags:[]).map(t=>String(t).trim()).filter(Boolean).filter(t=>{const k=t.toLowerCase();if(seen.has(k))return false;seen.add(k);return true})}
 function hydrate(){const d=load();books.forEach(b=>{if(d[b.id]&&Array.isArray(d[b.id].tags))b.tags=normalize(d[b.id].tags);else if(!Array.isArray(b.tags))b.tags=[]})}hydrate();
 const style=document.createElement('style');style.textContent=`.book-tags{margin:14px 0 18px}.book-tags-label{font-size:11px;letter-spacing:1px;color:#a99772;margin-bottom:7px}.book-tags-input-wrap{display:flex;gap:7px}.book-tags-input{flex:1;min-width:0;background:#203c32;border:1px solid #927e5266;color:#eee0bd;border-radius:6px;padding:9px}.book-tags-input:focus{outline:none;border-color:#c7a86b;box-shadow:0 0 0 1px #c7a86b55}.book-tags-add{border:1px solid #927e5266;background:#17352c;color:#e8d9b2;border-radius:6px;padding:7px 11px;cursor:pointer}.book-tags-help{font-size:10px;color:#8f8063;margin-top:5px}.book-tags-chips{display:flex;flex-wrap:wrap;gap:6px;margin-top:9px}.book-tag-chip{display:inline-flex;align-items:center;gap:6px;background:#29493d;border:1px solid #927e5266;color:#eadfbe;border-radius:999px;padding:5px 8px 5px 10px;font-size:11px}.book-tag-remove{border:0;background:none;color:#c8b78e;cursor:pointer;padding:0;font-size:14px;line-height:1}.book-tag-empty{font-size:11px;color:#8f8063;font-style:italic}`;document.head.appendChild(style);
 const notes=document.querySelector('#notes');if(!notes)return;
 const box=document.createElement('div');box.className='book-tags';box.id='bookTagsBox';box.innerHTML=`<div class="book-tags-label">ADDITIONAL TAGS</div><div class="book-tags-input-wrap"><input id="bookTagInput" class="book-tags-input" type="text" placeholder="e.g. mythology, Greek, retelling"><button id="bookTagAdd" class="book-tags-add" type="button">Add</button></div><div class="book-tags-help">Type a tag and press Enter. Add as many as you like.</div><div id="bookTagChips" class="book-tags-chips"></div>`;notes.insertAdjacentElement('afterend',box);
 const input=box.querySelector('#bookTagInput'),add=box.querySelector('#bookTagAdd'),chips=box.querySelector('#bookTagChips');
 function saveTags(){if(!currentBook)return;const d=load();(d[currentBook.id]||(d[currentBook.id]={})).tags=normalize(currentBook.tags);localStorage.setItem(KEY,JSON.stringify(d));window.dispatchEvent(new Event('library-tags-updated'));if(typeof window.renderCards==='function')window.renderCards()}
 function render(){chips.innerHTML='';if(!currentBook)return;currentBook.tags=normalize(currentBook.tags);if(!currentBook.tags.length){const e=document.createElement('span');e.className='book-tag-empty';e.textContent='No tags yet';chips.appendChild(e);return}currentBook.tags.forEach(tag=>{const c=document.createElement('span');c.className='book-tag-chip';const t=document.createElement('span');t.textContent=tag;const x=document.createElement('button');x.type='button';x.className='book-tag-remove';x.textContent='×';x.title='Remove '+tag;x.onclick=()=>{currentBook.tags=currentBook.tags.filter(v=>v.toLowerCase()!==tag.toLowerCase());saveTags();render()};c.append(t,x);chips.appendChild(c)})}
 function addTag(){if(!currentBook)return;const tag=input.value.trim();if(!tag)return;currentBook.tags=normalize([...(currentBook.tags||[]),tag]);input.value='';saveTags();render();input.focus()}
 add.onclick=addTag;input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addTag()}});
 const priorOpen=window.openBook;window.openBook=function(book){priorOpen(book);currentBook=book;const d=load();book.tags=normalize(d[book.id]?.tags||book.tags||[]);input.value='';render()};
})();