// Book removal controls: move a library book to Wishlist or permanently delete it.
(function(){
if(window.__bookActionsInitialized)return;window.__bookActionsInitialized=true;
const WISH_KEY='wishlistBooks',BOOK_KEY='manualBooks';let currentBook=null;
const style=document.createElement('style');style.textContent=`
.book-actions{margin:18px 0 4px;padding-top:16px;border-top:1px solid #927e5244;display:grid;grid-template-columns:1fr 1fr;gap:8px}.book-action-btn{padding:9px 8px;border-radius:6px;cursor:pointer;font-size:12px}.move-wish-btn{background:#203c32;border:1px solid #a88c5666;color:#e6d8b7}.delete-book-btn{background:#3b211f;border:1px solid #9d625c77;color:#e8c5be}.book-action-btn:hover{filter:brightness(1.12)}.delete-confirm{grid-column:1/-1;display:none;background:#251916;border:1px solid #9d625c66;border-radius:7px;padding:11px;color:#ddc8bd;font-size:12px}.delete-confirm.open{display:block}.delete-confirm p{margin:0 0 9px}.delete-confirm-actions{display:flex;gap:7px}.delete-confirm-actions button{flex:1;border-radius:5px;padding:7px;cursor:pointer}.confirm-delete{background:#713a34;border:1px solid #a7665e;color:#fff1eb}.cancel-delete{background:#17352c;border:1px solid #8f7a4d66;color:#ded0ad}
`;document.head.appendChild(style);
const panel=document.querySelector('#panel'),notes=document.querySelector('#notes');if(!panel||!notes)return;
const actions=document.createElement('div');actions.className='book-actions';actions.innerHTML=`<button type="button" class="book-action-btn move-wish-btn">♡ Move to Wishlist</button><button type="button" class="book-action-btn delete-book-btn">Delete Book</button><div class="delete-confirm"><p><b>Permanently delete this book?</b><br>This removes it from your library, shelf, notes, cover, and custom appearance.</p><div class="delete-confirm-actions"><button type="button" class="cancel-delete">Cancel</button><button type="button" class="confirm-delete">Delete Permanently</button></div></div>`;panel.appendChild(actions);
const moveBtn=actions.querySelector('.move-wish-btn'),deleteBtn=actions.querySelector('.delete-book-btn'),confirmBox=actions.querySelector('.delete-confirm'),cancelBtn=actions.querySelector('.cancel-delete'),confirmBtn=actions.querySelector('.confirm-delete');
function saveWishlist(list){localStorage.setItem(WISH_KEY,JSON.stringify(list))}
function cleanup(id){order=order.filter(x=>String(x)!==String(id));localStorage.setItem('bookOrder',JSON.stringify(order));if(notes&&typeof notes==='object'){delete notes[id];localStorage.setItem('bookNotes',JSON.stringify(notes))}const visuals=JSON.parse(localStorage.getItem('bookVisuals')||'{}');delete visuals[id];localStorage.setItem('bookVisuals',JSON.stringify(visuals));const details=JSON.parse(localStorage.getItem('bookDetailOverrides')||'{}');delete details[id];localStorage.setItem('bookDetailOverrides',JSON.stringify(details));}
function persistManual(){localStorage.setItem(BOOK_KEY,JSON.stringify(books.filter(b=>String(b.id).startsWith('m'))))}
function refresh(){if(typeof window.renderShelves==='function')window.renderShelves();if(typeof window.renderCards==='function')window.renderCards();const total=document.querySelector('#total');if(total)total.textContent=books.length;const read=document.querySelector('#readCount');if(read)read.textContent=books.filter(b=>b.read).length;panel.classList.remove('open');confirmBox.classList.remove('open')}
function removeFromBooks(id){const i=books.findIndex(b=>String(b.id)===String(id));if(i>=0)books.splice(i,1);persistManual()}
moveBtn.onclick=()=>{if(!currentBook)return;let wishlist=JSON.parse(localStorage.getItem(WISH_KEY)||'[]');if(!wishlist.some(x=>x.title===currentBook.title&&x.author===currentBook.author)){wishlist.push({...currentBook,id:'w'+Date.now(),read:false,rating:0,spice:0})}saveWishlist(wishlist);cleanup(currentBook.id);removeFromBooks(currentBook.id);refresh();window.dispatchEvent(new CustomEvent('wishlist-updated'))};
deleteBtn.onclick=()=>confirmBox.classList.add('open');cancelBtn.onclick=()=>confirmBox.classList.remove('open');confirmBtn.onclick=()=>{if(!currentBook)return;cleanup(currentBook.id);removeFromBooks(currentBook.id);refresh()};
const previousOpen=window.openBook;window.openBook=function(b){currentBook=b;confirmBox.classList.remove('open');return previousOpen(b)};
})();