// Spreadsheet import + persistence for the full library.
(function(){
const KEY='importedLibraryBooks',VERSION_KEY='libraryImportVersion';
const palette=['#563329','#233a32','#74543b','#25483d','#6a3f35','#25343a','#526146','#7a493d','#3d563c','#3c3035','#684333','#314d44'];
function loadSaved(){let saved=JSON.parse(localStorage.getItem(KEY)||'null');if(Array.isArray(saved)&&saved.length){books.splice(0,books.length,...saved);const stored=JSON.parse(localStorage.getItem('bookOrder')||'[]');const valid=new Set(saved.map(b=>String(b.id)));let kept=stored.filter(id=>valid.has(String(id)));saved.forEach(b=>{if(!kept.some(id=>String(id)===String(b.id)))kept.push(b.id)});order.splice(0,order.length,...kept);localStorage.setItem('bookOrder',JSON.stringify(order));/* IMPORTANT: Never delete bookShelfLayout here. Shelf positions are user-created data and must survive every normal page load. The layout is intentionally reset only when the user explicitly imports a new spreadsheet below. */if(typeof window.syncShelfLayout==='function')window.syncShelfLayout();const total=document.querySelector('#total');if(total)total.textContent=books.length;const read=document.querySelector('#readCount');if(read)read.textContent=books.filter(b=>b.read).length;}}
loadSaved();
function countSymbol(v,s){return v==null?0:(String(v).match(new RegExp(s,'gu'))||[]).length}
function truthy(v){if(v===true||v===1)return true;let s=String(v??'').trim().toLowerCase();return ['true','yes','y','read','1'].includes(s)}
function parseRows(rows){if(!rows.length)throw new Error('The spreadsheet is empty.');const head=rows[0].map(x=>String(x??'').trim());const col=n=>head.findIndex(h=>h.toLowerCase()===n.toLowerCase());const needed=['Title','Last Name','First Name','Format','Genre','Read','Rating','Stars','Spice'];if(needed.some(n=>col(n)<0))throw new Error('I could not find the expected columns: '+needed.join(', '));return rows.slice(1).filter(r=>String(r[col('Title')]??'').trim()).map((r,i)=>{let spiceRaw=r[col('Spice')],spice=null;if(spiceRaw!=null&&String(spiceRaw).trim()!=='')spice=String(spiceRaw).includes('🌵')?0:countSymbol(spiceRaw,'🌶');let author=[r[col('First Name')],r[col('Last Name')]].filter(x=>x!=null&&String(x).trim()).map(x=>String(x).trim()).join(' ');return{id:'imp'+String(i+1).padStart(3,'0'),title:String(r[col('Title')]??'').trim(),author:author||'Unknown Author',format:String(r[col('Format')]??'').trim(),genre:String(r[col('Genre')]??'').trim(),read:truthy(r[col('Read')]),contentRating:r[col('Rating')]==null||String(r[col('Rating')]).trim()===''?null:String(r[col('Rating')]).trim(),rating:countSymbol(r[col('Stars')],'⭐'),spice,color:palette[i%palette.length]}})}
function installButton(){const top=document.querySelector('#library .top');if(!top||document.querySelector('#importBooksBtn'))return;const input=document.createElement('input');input.type='file';input.id='librarySpreadsheetInput';input.accept='.xlsx,.xls,.csv';input.style.display='none';document.body.appendChild(input);const btn=document.createElement('button');btn.id='importBooksBtn';btn.className='add-book-btn';btn.textContent='⇧ Import Spreadsheet';btn.onclick=()=>input.click();top.appendChild(btn);input.onchange=async()=>{const file=input.files&&input.files[0];if(!file)return;try{if(typeof XLSX==='undefined')throw new Error('Spreadsheet reader is still loading. Wait a moment and try again.');const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:null,raw:true});const imported=parseRows(rows);if(!imported.length)throw new Error('No book rows were found.');localStorage.setItem(KEY,JSON.stringify(imported));localStorage.setItem(VERSION_KEY,'spreadsheet-'+Date.now());localStorage.setItem('bookOrder',JSON.stringify(imported.map(b=>b.id)));/* A NEW explicit import starts a fresh shelf layout. Normal refreshes never clear it. */localStorage.removeItem('bookShelfLayout');localStorage.removeItem('libraryShelfCount');alert('Success! '+imported.length+' books were imported. The library will reload now.');location.reload()}catch(err){console.error(err);alert('Import could not be completed: '+err.message)}finally{input.value=''}}}
function loadReader(){if(window.XLSX)return;const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.async=true;document.head.appendChild(s)}
loadReader();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installButton);else installButton();
})();