// Full local-library export/restore. Keeps user data portable and recoverable.
(function(){
if(window.__libraryBackupInitialized)return;window.__libraryBackupInitialized=true;
const KEYS=['importedLibraryBooks','libraryImportVersion','bookOrder','bookNotes','bookVisuals','bookDetailOverrides','manualBooks','libraryWishlistV2','wishlistBooks','bookShelfLayout','bookShelfLayoutBackup','libraryShelfCount','libraryDecor','libraryName','readingGoal','readingGoalData','readingGoalSettings','statsColors','readingStatsColors','audiobookStats','audiobookMinutes'];
const style=document.createElement('style');style.textContent=`.backup-btn{background:#1b392f;border:1px solid #a58b5866;color:#eadcb8;border-radius:20px;padding:9px 14px;cursor:pointer}.backup-btn:hover{background:#29483d}.backup-group{display:flex;gap:7px;flex-wrap:wrap}`;document.head.appendChild(style);
function snapshot(){const data={app:'my-conservatory-library',schemaVersion:2,exportedAt:new Date().toISOString(),storage:{}};KEYS.forEach(k=>{const v=localStorage.getItem(k);if(v!==null)data.storage[k]=v});return data}
function exportBackup(){const data=snapshot();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');const d=new Date(),stamp=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');a.href=URL.createObjectURL(blob);a.download='my-library-backup-'+stamp+'.json';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}
function restoreBackup(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data||data.app!=='my-conservatory-library'||!data.storage||typeof data.storage!=='object')throw new Error('This is not a valid My Library backup file.');const layoutRaw=data.storage.bookShelfLayout||data.storage.bookShelfLayoutBackup;let layout=null;try{layout=JSON.parse(layoutRaw||'null')}catch(e){};const booksRaw=data.storage.importedLibraryBooks;let savedBooks=null;try{savedBooks=JSON.parse(booksRaw||'null')}catch(e){};const manualRaw=data.storage.manualBooks;let manualBooks=null;try{manualBooks=JSON.parse(manualRaw||'null')}catch(e){};const assigned=layout&&typeof layout==='object'?Object.keys(layout).length:0;const count=(Array.isArray(savedBooks)?savedBooks.length:0)+(Array.isArray(manualBooks)?manualBooks.length:0);const ok=confirm('Restore this library backup?\n\nBackup contains '+count+' library books and '+assigned+' saved shelf assignments.\n\nThis will replace the library data currently stored in this browser.');if(!ok)return;Object.keys(data.storage).forEach(k=>{if(KEYS.includes(k)&&typeof data.storage[k]==='string')localStorage.setItem(k,data.storage[k])});if(layoutRaw){localStorage.setItem('bookShelfLayout',layoutRaw);localStorage.setItem('bookShelfLayoutBackup',layoutRaw)}alert('Backup restored successfully. The library will reload now.');location.reload()}catch(err){console.error(err);alert('Backup could not be restored: '+err.message)}};reader.readAsText(file)}
function install(){const top=document.querySelector('#shelf .top');if(!top||document.querySelector('#exportLibraryBackup'))return;const group=document.createElement('span');group.className='backup-group';const exp=document.createElement('button');exp.id='exportLibraryBackup';exp.className='backup-btn';exp.type='button';exp.textContent='↓ Export Backup';exp.title='Download a backup of your books, shelf positions, notes, appearance settings, wishlist and decor';const imp=document.createElement('button');imp.id='restoreLibraryBackup';imp.className='backup-btn';imp.type='button';imp.textContent='↥ Restore Backup';imp.title='Restore your library from a previously exported backup';const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.style.display='none';exp.onclick=exportBackup;imp.onclick=()=>input.click();input.onchange=()=>{if(input.files&&input.files[0])restoreBackup(input.files[0]);input.value=''};group.append(exp,imp,input);top.appendChild(group)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();