// Date-aware reading goal tracker + finished date field.
(function(){
 if(window.__readingGoalInitialized)return;window.__readingGoalInitialized=true;
 const DETAIL_KEY='bookDetailOverrides',GOAL_KEY='readingGoalSettings',COLOR_KEY='readingGoalColors';
 function details(){try{return JSON.parse(localStorage.getItem(DETAIL_KEY)||'{}')}catch(e){return {}}}
 function saveFinished(book,value){const d=details();(d[book.id]||(d[book.id]={})).finishedDate=value||null;localStorage.setItem(DETAIL_KEY,JSON.stringify(d));book.finishedDate=value||null;window.dispatchEvent(new Event('library-stats-updated'))}
 function hydrate(){const d=details();books.forEach(b=>{if(d[b.id]&&d[b.id].finishedDate!==undefined)b.finishedDate=d[b.id].finishedDate})}hydrate();
 const style=document.createElement('style');style.textContent=`.finished-date-row{margin:-8px 0 18px}.finished-date-label{font-size:11px;letter-spacing:1px;color:#a99772;margin-bottom:5px}.finished-date-input{width:100%;background:#203c32;border:1px solid #927e5266;color:#eee0bd;border-radius:6px;padding:9px}.goal-card{grid-column:1/-1}.goal-settings{display:grid;grid-template-columns:repeat(3,minmax(130px,1fr));gap:10px;margin:4px 0 18px}.goal-field{display:grid;gap:5px}.goal-field label{font-size:11px;letter-spacing:1px;color:#a99772}.goal-field input{background:#203c32;border:1px solid #927e5266;color:#eee0bd;border-radius:6px;padding:9px;min-width:0}.goal-layout{display:grid;grid-template-columns:210px 1fr;gap:24px;align-items:center}.goal-ring{width:190px;height:190px;border-radius:50%;position:relative;margin:auto;box-shadow:0 8px 22px #0005}.goal-ring:after{content:'';position:absolute;inset:38px;border-radius:50%;background:#122d25}.goal-center{position:absolute;inset:0;z-index:1;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.goal-number{font-size:34px;color:#eadcb8}.goal-caption{font-size:11px;letter-spacing:1px;color:#a99772}.goal-summary{color:#dfd2b3;font-size:17px;margin-bottom:8px}.goal-dates{color:#a99772;font-size:12px;margin-bottom:15px}.goal-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.goal-btn{padding:8px 12px;border:1px solid #927e5266;background:#102a23;color:#d9caa5;border-radius:6px;cursor:pointer}.goal-color-controls{display:flex;gap:14px;flex-wrap:wrap;margin-top:15px;padding-top:14px;border-top:1px solid #8e794c33}.goal-color-control{display:flex;align-items:center;gap:7px;color:#bca978;font-size:11px}.goal-color-control input{width:28px;height:28px;border:0;background:transparent;padding:0}@media(max-width:700px){.goal-settings,.goal-layout{grid-template-columns:1fr}}`;document.head.appendChild(style);
 // Add finished date when any book popout opens. Date only counts if the book is Read.
 function addFinishedDate(book){let old=document.querySelector('#finishedDateRow');if(old)old.remove();const cr=document.querySelector('#contentRatingRow');if(!cr)return;const row=document.createElement('div');row.id='finishedDateRow';row.className='finished-date-row';row.innerHTML=`<div class="finished-date-label">DATE FINISHED</div><input id="inlineFinishedDate" class="finished-date-input" type="date"><div style="font-size:10px;color:#8f8063;margin-top:4px">Used for reading goals when this book is marked Read.</div>`;cr.insertAdjacentElement('afterend',row);const input=row.querySelector('input');input.value=book.finishedDate||'';input.onchange=()=>saveFinished(book,input.value)}
 const previousOpen=window.openBook;window.openBook=function(book){previousOpen(book);hydrate();addFinishedDate(book)};
 // If a book is newly marked Read and has no finish date, default to today; user can edit it.
 document.addEventListener('change',e=>{if(e.target&&e.target.id==='inlineRead'){setTimeout(()=>{const title=document.querySelector('#inlineBookTitle')?.value;const author=document.querySelector('#inlineBookAuthor')?.value;const book=books.find(b=>b.title===title&&b.author===author);if(!book)return;if(e.target.value==='true'&&!book.finishedDate){const today=new Date();const local=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().slice(0,10);saveFinished(book,local);const inp=document.querySelector('#inlineFinishedDate');if(inp)inp.value=local}window.dispatchEvent(new Event('library-stats-updated'))},0)}});
 const grid=document.querySelector('#statsReadingGrid');if(!grid)return;
 let goal=Object.assign({target:12,start:'',end:''},JSON.parse(localStorage.getItem(GOAL_KEY)||'{}'));let palette=Object.assign({complete:'#c7a86b',remaining:'#315443'},JSON.parse(localStorage.getItem(COLOR_KEY)||'{}'));
 const card=document.createElement('section');card.className='reading-chart-card goal-card';card.innerHTML=`<h2>Reading Goal</h2><div class="reading-chart-sub">Set a goal for a specific time frame. Only books marked Read with a Date Finished inside that range count.</div><div class="goal-settings"><div class="goal-field"><label>BOOK GOAL</label><input id="goalTarget" type="number" min="1" step="1"></div><div class="goal-field"><label>START DATE</label><input id="goalStart" type="date"></div><div class="goal-field"><label>END DATE</label><input id="goalEnd" type="date"></div></div><div class="goal-layout"><div class="goal-ring" id="goalRing"><div class="goal-center"><div class="goal-number" id="goalNumber">0 / 0</div><div class="goal-caption">BOOKS READ</div></div></div><div><div class="goal-summary" id="goalSummary">Set your reading goal above.</div><div class="goal-dates" id="goalDates"></div><div class="reading-legend"><div class="reading-legend-row"><span class="reading-marker" id="goalDoneMarker"></span><span class="reading-legend-name">Completed</span><span class="reading-legend-count" id="goalDone">0</span></div><div class="reading-legend-row"><span class="reading-marker" id="goalRemainMarker"></span><span class="reading-legend-name">Remaining</span><span class="reading-legend-count" id="goalRemain">0</span></div></div><div class="goal-color-controls"><label class="goal-color-control">Completed <input id="goalCompleteColor" type="color"></label><label class="goal-color-control">Remaining <input id="goalRemainingColor" type="color"></label></div><div class="goal-actions"><button class="goal-btn" id="newGoal">Reset / New Goal</button></div></div></div>`;grid.appendChild(card);
 const target=card.querySelector('#goalTarget'),start=card.querySelector('#goalStart'),end=card.querySelector('#goalEnd'),cc=card.querySelector('#goalCompleteColor'),rc=card.querySelector('#goalRemainingColor');target.value=goal.target||12;start.value=goal.start||'';end.value=goal.end||'';cc.value=palette.complete;rc.value=palette.remaining;
 function persist(){goal={target:Math.max(1,Number(target.value)||1),start:start.value,end:end.value};localStorage.setItem(GOAL_KEY,JSON.stringify(goal));render()}
 function render(){hydrate();const t=Math.max(1,Number(target.value)||1),s=start.value,e=end.value;const count=(s&&e)?books.filter(b=>b.read&&b.finishedDate&&b.finishedDate>=s&&b.finishedDate<=e).length:0;const shown=Math.min(count,t),remaining=Math.max(0,t-count),pct=Math.min(100,count/t*100);card.querySelector('#goalNumber').textContent=count+' / '+t;card.querySelector('#goalDone').textContent=count;card.querySelector('#goalRemain').textContent=remaining;card.querySelector('#goalDoneMarker').style.background=palette.complete;card.querySelector('#goalRemainMarker').style.background=palette.remaining;card.querySelector('#goalRing').style.background=`conic-gradient(${palette.complete} 0 ${pct}%,${palette.remaining} ${pct}% 100%)`;card.querySelector('#goalSummary').textContent=!s||!e?'Choose a start and end date to begin.':count>=t?'Goal complete! You reached '+count+' books.':remaining+' book'+(remaining===1?'':'s')+' to go';card.querySelector('#goalDates').textContent=s&&e?s+' through '+e:''}
 target.onchange=persist;start.onchange=persist;end.onchange=persist;cc.oninput=e=>{palette.complete=e.target.value;localStorage.setItem(COLOR_KEY,JSON.stringify(palette));render()};rc.oninput=e=>{palette.remaining=e.target.value;localStorage.setItem(COLOR_KEY,JSON.stringify(palette));render()};card.querySelector('#newGoal').onclick=()=>{target.value=12;start.value='';end.value='';localStorage.removeItem(GOAL_KEY);render()};window.addEventListener('library-stats-updated',render);document.querySelectorAll('.nav button').forEach(b=>{if(b.dataset.view==='stats')b.addEventListener('click',()=>setTimeout(render,0))});render();
})();