// Independent shelf layout + decor drag/drop.
(function(){
function startDecor(){
 if(typeof window.renderShelves!=='function'||!window.DECOR_ASSETS)return;
 const LAYOUT_KEY='bookShelfLayout',BACKUP_KEY='bookShelfLayoutBackup',COUNT_KEY='libraryShelfCount';
 const SORT_SHELF_SIZE=25;
 const DECOR_BASELINE={pothos:-9,fern:-3,candle:-2,candlestick:-2,lamp:-3,lantern:-12,bust:-4,globe:-4,hourglass:-5,crystal:-3,bookstack:-8,bookend:-12,botanical:-3,vase:-2,driedflowers:-3,teacup:-6,jar:0,cloche:-14,cat:-6,booksCandles:-16,booksIvy:-16};
 const REALISTIC_SCALE={pothos:1.24,globe:1.24,cat:1.24,bankerLamp:1.3924,antiqueBooks:1.15,booksCandles:2.05,booksIvy:1.90};
 let decorItems=JSON.parse(localStorage.getItem('libraryDecor')||'null');if(!Array.isArray(decorItems))decorItems=[{id:'d1',type:'pothos',shelf:0,pos:6},{id:'d2',type:'candle',shelf:1,pos:6},{id:'d3',type:'fern',shelf:2,pos:6}];
 function readObj(key){try{const x=JSON.parse(localStorage.getItem(key)||'null');return x&&typeof x==='object'&&!Array.isArray(x)?x:null}catch(e){return null}}
 let primary=readObj(LAYOUT_KEY),backup=readObj(BACKUP_KEY);let layout=(!primary&&backup)?backup:(!backup&&primary)?primary:(primary&&backup&&Object.keys(backup).length>Object.keys(primary).length?backup:primary);
 let shelfCount=Number(localStorage.getItem(COUNT_KEY)||0),draggedDecor=null;
 const numericSeed=id=>parseInt(String(id).replace(/\D/g,'').slice(-6),10)||1;function bookKey(id){return String(id)}function getSlot(id){return layout&&layout[bookKey(id)]}function setSlot(id,value){layout[bookKey(id)]=value}
 const saveLayout=()=>{const text=JSON.stringify(layout);localStorage.setItem(LAYOUT_KEY,text);localStorage.setItem(BACKUP_KEY,text);localStorage.setItem(COUNT_KEY,String(shelfCount));updateStatus()},saveDecor=()=>localStorage.setItem('libraryDecor',JSON.stringify(decorItems));
 function migrate(){const ids=ordered().map(b=>b.id);if(!layout||typeof layout!=='object'){layout={};ids.forEach((id,i)=>setSlot(id,{shelf:Math.floor(i/6),pos:i%6}));}ids.forEach(id=>{if(!getSlot(id)){let used=Object.values(layout).filter(x=>x&&Number.isFinite(Number(x.shelf)));let last=used.length?Math.max(...used.map(x=>Number(x.shelf))):0;setSlot(id,{shelf:last,pos:999});}});const highest=Math.max(0,...Object.values(layout).map(x=>Number(x&&x.shelf)||0),...decorItems.map(d=>Number(d.shelf)||0));shelfCount=Math.max(3,shelfCount||0,highest+1);saveLayout()}
 const style=document.createElement('style');style.textContent=`.decor-wrap{height:100%;display:flex;align-items:flex-end;justify-content:center;flex:0 0 auto;position:relative;margin:0;overflow:visible;z-index:2}.decor-wrap:after{content:'';position:absolute;left:10%;right:10%;bottom:0;height:4px;background:radial-gradient(ellipse at center,#08060466 0%,#08060433 45%,transparent 72%);filter:blur(2px);pointer-events:none}.decor{object-fit:contain;object-position:center bottom;display:block;margin:0;filter:drop-shadow(1px 3px 2px #0007) saturate(.9) contrast(.96) brightness(.94);cursor:grab;position:relative;z-index:1;max-height:190px}.decor:hover{transform:scale(1.018);transform-origin:center bottom}.decor-button,.add-shelf-btn{background:#1b392f;border:1px solid #a58b5866;color:#eadcb8;border-radius:20px;padding:9px 14px;cursor:pointer}.add-shelf-wrap{text-align:center;padding:16px 0 5px}.add-shelf-btn{background:#4b3423}.layout-status{font-size:11px;color:#b9a77e;padding:7px 10px;border:1px solid #8f7a4d44;border-radius:16px;background:#102a23}.layout-status.good{color:#c9d8b5}.decor-drawer{position:fixed;left:210px;right:0;bottom:0;z-index:20;background:#0b211cf5;border-top:1px solid #a88c56;box-shadow:0 -15px 35px #0009;padding:16px 22px 20px;transform:translateY(105%);transition:.25s}.decor-drawer.open{transform:none}.decor-head{display:flex;justify-content:space-between}.decor-head h3{margin:0;color:#ead8aa;font-weight:normal}.decor-close{background:none;border:0;color:#ead8aa;font-size:25px}.decor-grid{display:flex;gap:12px;overflow-x:auto;padding:12px 2px}.decor-choice{min-width:105px;background:#122d25;border:1px solid #8e794c55;border-radius:8px;padding:8px;color:#cfc3a5;cursor:pointer}.decor-choice img{width:82px;height:86px;object-fit:contain}.decor-choice small{display:block;margin-top:4px}.shelf.decor-over{box-shadow:0 10px 10px #120a07,inset 0 0 24px #c7a86b55!important}.shelf:empty:before{content:'Empty shelf';color:#8d7c5d55;font-style:italic;margin:auto auto 18px;font-size:12px}.shelf-live-controls{position:absolute;right:8px;top:8px;z-index:50;display:flex;gap:5px}.shelf-live-controls button{width:28px;height:28px;padding:0;border-radius:50%;border:1px solid #a88c5688;background:#102a23ee;color:#e7d6aa;cursor:pointer}.shelf-live-controls button:disabled{opacity:.2;cursor:default}.shelf-live-number{position:absolute;left:8px;top:10px;color:#a9977277;font-size:10px;letter-spacing:1px;pointer-events:none}@media(max-width:760px){.decor-drawer{left:0}.decor{max-height:165px}}`;document.head.appendChild(style);
 const top=document.querySelector('#shelf .top');if(top&&!document.querySelector('#decorBtn')){let b=document.createElement('button');b.id='decorBtn';b.className='decor-button';b.textContent='✦ Decorate';top.appendChild(b);let st=document.createElement('span');st.id='layoutStatus';st.className='layout-status';top.appendChild(st)}
 const sort=document.querySelector('#sort');if(sort&&!sort.querySelector('option[value="physicalFirst"]')){sort.insertAdjacentHTML('beforeend','<option value="physicalFirst">Format — Physical first</option><option value="digitalFirst">Format — Digital first</option>')}
 function updateStatus(){const st=document.querySelector('#layoutStatus');if(!st||!layout)return;const current=books.filter(b=>getSlot(b.id)).length;const spread=new Set(books.map(b=>getSlot(b.id)).filter(Boolean).map(x=>Number(x.shelf))).size;st.textContent='✓ Saved layout: '+current+'/'+books.length+' books · '+spread+' shelves';st.classList.toggle('good',current===books.length)}
 const drawer=document.createElement('div');drawer.className='decor-drawer';drawer.innerHTML='<div class="decor-head"><h3>Conservatory Decor Collection · Decor 2.0</h3><button class="decor-close">×</button></div><div class="decor-grid"></div>';document.body.appendChild(drawer);const grid=drawer.querySelector('.decor-grid');
 function normalizeShelf(s){let arr=books.filter(b=>getSlot(b.id)&&Number(getSlot(b.id).shelf)===s).sort((a,b)=>(Number(getSlot(a.id).pos)||0)-(Number(getSlot(b.id).pos)||0));arr.forEach((b,i)=>setSlot(b.id,{shelf:s,pos:i}))}
 function moveBook(id,s,pos){const b=books.find(x=>String(x.id)===String(id));if(!b)return;const old=getSlot(b.id)?.shelf;setSlot(b.id,{shelf:s,pos:pos});if(old!==undefined)normalizeShelf(Number(old));normalizeShelf(s);saveLayout();dragged=null;refresh()}
 function swapShelves(a,b){if(a===b||a<0||b<0||a>=shelfCount||b>=shelfCount)return;Object.keys(layout).forEach(id=>{let s=Number(layout[id]?.shelf);if(s===a)layout[id].shelf=b;else if(s===b)layout[id].shelf=a});decorItems.forEach(d=>{let s=Number(d.shelf);if(s===a)d.shelf=b;else if(s===b)d.shelf=a});saveLayout();saveDecor();refresh()}
 function addShelfControls(sh,s){let label=document.createElement('span');label.className='shelf-live-number';label.textContent='SHELF '+(s+1);sh.appendChild(label);let c=document.createElement('div');c.className='shelf-live-controls';let up=document.createElement('button');up.type='button';up.textContent='↑';up.title='Move entire shelf up';up.disabled=s===0;up.onclick=e=>{e.preventDefault();e.stopPropagation();swapShelves(s,s-1)};let down=document.createElement('button');down.type='button';down.textContent='↓';down.title='Move entire shelf down';down.disabled=s===shelfCount-1;down.onclick=e=>{e.preventDefault();e.stopPropagation();swapShelves(s,s+1)};c.append(up,down);sh.appendChild(c)}
 function formatGroup(b){const f=String(b.format||'').toLowerCase();return /(kindle|ebook|e-book|digital)/.test(f)?'digital':'physical'}
 function renderDecorShelves(){migrate();let q=document.querySelector('#search').value.toLowerCase(),mode=document.querySelector('#sort').value,root=document.querySelector('#shelves');root.innerHTML='';if(mode!=='custom'||q){let list=ordered().filter(b=>(b.title+' '+b.author+' '+b.genre+' '+b.format).toLowerCase().includes(q));if(mode==='physicalFirst'||mode==='digitalFirst'){const wanted=mode==='physicalFirst'?'physical':'digital';list.sort((a,b)=>{const ag=formatGroup(a)===wanted?0:1,bg=formatGroup(b)===wanted?0:1;return ag-bg||String(a.title||'').localeCompare(String(b.title||''))})}else if(mode!=='custom')list.sort((a,b)=>(a[mode]||'').localeCompare(b[mode]||''));for(let s=0;s<Math.max(1,Math.ceil(list.length/SORT_SHELF_SIZE));s++){let sh=document.createElement('div');sh.className='shelf';list.slice(s*SORT_SHELF_SIZE,s*SORT_SHELF_SIZE+SORT_SHELF_SIZE).forEach(b=>sh.appendChild(makeBook(b,s,999,false)));root.appendChild(sh)}return}for(let s=0;s<shelfCount;s++){let sh=document.createElement('div');sh.className='shelf';sh.dataset.shelf=s;let shelfBooks=books.filter(b=>getSlot(b.id)&&Number(getSlot(b.id).shelf)===s).sort((a,b)=>(Number(getSlot(a.id).pos)||0)-(Number(getSlot(b.id).pos)||0));let shelfDecor=decorItems.filter(d=>Number(d.shelf)===s).sort((a,b)=>a.pos-b.pos);sh.ondragover=e=>{e.preventDefault();sh.classList.add('decor-over')};sh.ondragleave=()=>sh.classList.remove('decor-over');sh.ondrop=e=>{e.preventDefault();sh.classList.remove('decor-over');if(draggedDecor){let d=decorItems.find(x=>x.id===draggedDecor);if(d){d.shelf=s;d.pos=999;saveDecor()}draggedDecor=null;refresh();return}if(dragged)moveBook(dragged,s,shelfBooks.length)};const addDecor=slot=>shelfDecor.filter(d=>Math.min(d.pos,shelfBooks.length)===slot).forEach(d=>{let w=document.createElement('span');w.className='decor-wrap';let el=document.createElement('img');el.className='decor';el.src=DECOR_ASSETS[d.type];let sz=(window.DECOR_SIZES&&DECOR_SIZES[d.type])||{w:72,h:112};let scale=1.24*(REALISTIC_SCALE[d.type]||1),renderW=Math.round(sz.w*scale),renderH=Math.round(sz.h*scale);el.style.width=renderW+'px';el.style.height=renderH+'px';el.style.marginBottom=(DECOR_BASELINE[d.type]??-2)+'px';w.style.width=Math.round(renderW*(d.type==='bookend'?.62:.82))+'px';el.draggable=true;el.title=(DECOR_LABELS[d.type]||'Decor')+' — drag to move · double-click to remove';el.ondragstart=e=>{draggedDecor=d.id;dragged=null;e.dataTransfer.effectAllowed='move'};el.ondblclick=e=>{e.stopPropagation();decorItems=decorItems.filter(x=>x.id!==d.id);saveDecor();refresh()};w.appendChild(el);sh.appendChild(w)});for(let i=0;i<=shelfBooks.length;i++){addDecor(i);if(i<shelfBooks.length)sh.appendChild(makeBook(shelfBooks[i],s,i,true))}addShelfControls(sh,s);root.appendChild(sh)}}
 function makeBook(b,s,i,custom){let seed=numericSeed(b.id),el=document.createElement('button');el.className='book';el.draggable=true;el.dataset.id=b.id;el.textContent=b.title;el.style.background=b.color;el.style.height=(135+(seed*13)%50)+'px';el.style.width=(28+(seed*7)%16)+'px';el.onclick=()=>openBook(b);el.ondragstart=e=>{dragged=b.id;draggedDecor=null;e.dataTransfer.effectAllowed='move'};el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();e.stopPropagation();if(custom&&dragged&&String(dragged)!==String(b.id))moveBook(dragged,s,i);else if(draggedDecor){let d=decorItems.find(x=>x.id===draggedDecor);if(d){d.shelf=s;d.pos=i;saveDecor()}draggedDecor=null;refresh()}};return el}
 function refresh(){renderDecorShelves();const visuals=JSON.parse(localStorage.getItem('bookVisuals')||'{}');document.querySelectorAll('.book[data-id]').forEach(el=>{let b=books.find(x=>String(x.id)===String(el.dataset.id));if(!b)return;let v=visuals[b.id]||{},seed=numericSeed(b.id);el.style.background=v.color||b.color;el.style.height=(v.height||135+(seed*13)%50)+'px';el.style.width=(v.width||28+(seed*7)%16)+'px'});updateStatus()}
 window.renderShelves=refresh;window.syncShelfLayout=()=>{migrate();refresh()};if(sort)sort.onchange=refresh;const search=document.querySelector('#search');if(search)search.oninput=refresh;
 let wrap=document.createElement('div');wrap.className='add-shelf-wrap';let add=document.createElement('button');add.className='add-shelf-btn';add.textContent='+ Add Shelf';add.onclick=()=>{shelfCount++;saveLayout();refresh()};wrap.appendChild(add);document.querySelector('.bookcase').appendChild(wrap);Object.keys(DECOR_ASSETS).forEach(type=>{let c=document.createElement('button');c.className='decor-choice';c.innerHTML=`<img src="${DECOR_ASSETS[type]}" alt=""><small>${DECOR_LABELS[type]||type}</small>`;c.onclick=()=>{decorItems.push({id:'d'+Date.now()+Math.random(),type,shelf:0,pos:0});saveDecor();refresh()};grid.appendChild(c)});document.querySelector('#decorBtn').onclick=()=>drawer.classList.toggle('open');drawer.querySelector('.decor-close').onclick=()=>drawer.classList.remove('open');migrate();refresh();
}
function bootShelfSystem(){if(window.DECOR_ASSETS)startDecor();else{let s=document.createElement('script');s.src='decor-assets.js?v=2';s.onload=startDecor;document.head.appendChild(s)}}setTimeout(bootShelfSystem,50);
})();